### ISSUE TITLE
SRTM reader does not work well in South And East

### ISSUE THREAD

**Issue by muhammetasan** [QDeltaSoft/qradiopredict#6]
I am using srtmreader class. When I set coordinates to 

> (-23.4,34.3)  

` _latitude_secs = -46.399999999999999`
and in `readHeight() `function 

`  unsigned temp_row  = (unsigned) round(_latitude_secs *3600/3); `
 where `temp_row` is expected be row number in binary file but its value is `4294911616` in `1201*1201 `file.

**Comment by kantooon** [comment]
Thank you for reporting this, it is likely there is bug in the math code which converts the coordinates. I will investigate this issue.

**Comment by kantooon** [comment]
Should be fixed now in the latest commit. There was indeed a bug in the logic handling of negative coordinates. Please verify fix.

**Comment by muhammetasan** [comment]
Thanks for interest. It seems that with absolute values position is staying inside file .But we should be sure that , reported position is reading correct location . As the filename is lowerleft corner of tile, in south side is true ? In north,for instance,  N40.1 is very close to bottom side of tile . But in the case of south S40.1 should be close to top side of tile ? There is no explanation for this in this [documentation](http://dds.cr.usgs.gov/srtm/version2_1/Documentation/SRTM_Topo.pdf)

**Comment by kantooon** [comment]
Well, thank you for having the patience to look into this. I tested the code with actual data and I believe I finally got it right (this time). Regarding SRTM tiles, they all start from the lower left coner. If you have a tile with say -0.2,0.6, the degrees will be W1N0 and the seconds will be 0.8 and 0.6. Hope this explains better. Cheers!
